// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_2JRqKjwuQ2JxefaJAYzorQxhBbkP9bM',
    appId: '1:60822150263:web:ca027f800c280a9d5aba72',
    messagingSenderId: '60822150263',
    projectId: 'ai-food-delivery-app',
    authDomain: 'ai-food-delivery-app.firebaseapp.com',
    storageBucket: 'ai-food-delivery-app.firebasestorage.app',
    measurementId: 'G-K2E2V7PV2R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCh2XZJ2pKgTknWNfUkFc_j5pjVw_u1h8',
    appId: '1:60822150263:android:2b838a853b075ef85aba72',
    messagingSenderId: '60822150263',
    projectId: 'ai-food-delivery-app',
    storageBucket: 'ai-food-delivery-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqQyTWcnbp2_JwSe8IxiMqvrSY2p2mYgo',
    appId: '1:60822150263:ios:c142aa61eaaa07685aba72',
    messagingSenderId: '60822150263',
    projectId: 'ai-food-delivery-app',
    storageBucket: 'ai-food-delivery-app.firebasestorage.app',
    iosBundleId: 'com.example.aiFoodDeliveryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqQyTWcnbp2_JwSe8IxiMqvrSY2p2mYgo',
    appId: '1:60822150263:ios:c142aa61eaaa07685aba72',
    messagingSenderId: '60822150263',
    projectId: 'ai-food-delivery-app',
    storageBucket: 'ai-food-delivery-app.firebasestorage.app',
    iosBundleId: 'com.example.aiFoodDeliveryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_2JRqKjwuQ2JxefaJAYzorQxhBbkP9bM',
    appId: '1:60822150263:web:c874791283a361855aba72',
    messagingSenderId: '60822150263',
    projectId: 'ai-food-delivery-app',
    authDomain: 'ai-food-delivery-app.firebaseapp.com',
    storageBucket: 'ai-food-delivery-app.firebasestorage.app',
    measurementId: 'G-0GV7SFDXKR',
  );
}
